name: {{project.name}}

profile: {{project.profile_name}}

on-run-end:
  {% if project.warehouse == 'redshift' %}
  - "{% raw %}{% for schema in schemas %}{% endraw %}"
  {% endif %}
  {% if project.warehouse == 'snowflake' %}
  - "snowflake grant statements"
  {% endif %}
models:
  {% if project.warehouse == 'redshift' %}
  bind: false
  {% endif %}
  {{project.name}}: